### ISSUE TITLE
Where should we download wikipedia dumps ?

### ISSUE THREAD

**Issue by enzopoggio** [akb89/nima#2]
Hi,
I don't know where to download wikipedia dumps!
For the moment I'm trying to download it on my personal server.
**It's going to take a while !!**: 181300K ..........  1%  559K 8h1m (14.1 go)

**Is this the good version ?**
https://dumps.wikimedia.org/other/static_html_dumps/current/en/wikipedia-en-html.tar.7z
Should we download it on a Unige's server once and work on it at distance ?

Enzo

PS: Peut-on écrire en français dans les issues ?

**Comment by minimalparts** [comment]
Hi Enzo,

Stop everything -- you want the XML dump :) (https://dumps.wikimedia.org/enwiki/20170420/enwiki-20170420-pages-articles.xml.bz2)

Re. the server, I let Alexandre reply for details. But yes, you should use the unige server.
Aurelie

**Comment by enzopoggio** [comment]
Thx I stopped!

**Comment by akb89** [comment]
You will find three samples of XML wikidumps [here](http://129.194.22.116/~kabbach/public/samples/). 
Let me know if they work fine with wikiextractor. 
We will run NiMa on CLCL servers with the full dumps once it's in v1.0
