### ISSUE TITLE
Docstrings framework?

### ISSUE THREAD

**Issue by akb89** [akb89/nima#21]
I am considering using [Sphinx](http://www.sphinx-doc.org/en/stable/index.html) for documenting our applications. This would require reST-style formats for docstrings (see [here](http://stackoverflow.com/questions/3898572/what-is-the-standard-python-docstring-format))

What do you think? 

If you have a better suggestion, don't hesitate.

**Comment by minimalparts** [comment]
Personally all for it. I love Sphinx.

**Comment by akb89** [comment]
Let's go for Sphinx then!
