### ISSUE TITLE
Problème test extract

### ISSUE THREAD

**Issue by damdamo** [akb89/nima#26]
J'ai fait la plupart des tests et il me manque le test de comportement pour la fonction extract.
Je veux tester que l'output existe bien dans un dossier que j'ai défini dans test.
Le test ne fonctionne pas chez moi à cause de l'erreur avec wikiextractor que nous avions vu aujourd'hui.

Screen: http://hpics.li/7dd0fdc

Il semblerait que ce n'est pas la bonne fonction qui est appelée. Je ne sais donc pas vraiment quoi faire.

**Comment by akb89** [comment]
Ok. I'll take a loot at it and get back to you.

**Comment by damdamo** [comment]
Je n'ai toujours pas réussi à résoudre le soucis, au pire on le mettra dans le TODO. Par contre cela me pose problème pour passer avec le linter.

**Comment by damdamo** [comment]
J'ai corrigé le problème de conflit en renommant wikiextractor par nima_wikiextractor. Le problème venait bien de là et maintenant tout fonctionne correctement.

**Comment by akb89** [comment]
I'm on it

**Comment by damdamo** [comment]
Comment je fais vu que nous avons toujours ce problème et que je ne sais pas si celui-ci sera résolu avant ce soir? 
Est-ce que je commente les tests qui utilisent wikiextract vu que ceux-ci ne peuvent pas passer? Sachant que cela empêchera aussi le build de passer.

**Comment by akb89** [comment]
Non ce bug je m'en occupe, je commenterai éventuellement pour que le build passe si ça ne tient qu'à ça.

**Comment by damdamo** [comment]
Ce problème apparaît à un autre endroit où nous avons deux conflits de noms.
Voici un screen:
http://hpics.li/4801db8
On veut importer nltk.stem.lancaster mais le soucis c'est qu'il croit qu'on importe le fichier du même nom. Donc si je ne peux pas renommer le nom du fichier pour éviter le conflit comment je peux faire?

**Comment by akb89** [comment]
I cannot reproduce the error. Do we have the same linter version? 
I have:
```
pylint 1.7.1
pydocstyle 2.0.0
pycodestyle 2.3.1
```

**Comment by damdamo** [comment]
J'ai:
```bash
pylint 1.7.1
pydocstyle 2.0.0
pycodestyle 2.3.1
```

Donc exactement pareil

**Comment by akb89** [comment]
Le build sur travis (voir [ici](https://travis-ci.org/akb89/nima/jobs/231215371)) ne montre pas l'erreur (on a le même output qu'en utilisant `pylint nima`). 
J'ai ajouté les dépendances au `setup.py`.

**Comment by akb89** [comment]
Le bug vient de ce que les packages n'ont pas été correctement installés sur le système. 
Cela ne devrait pas affecter le build tant que les dépendances ont été correctement ajoutées au setup.py. 

Closing this issue
