### ISSUE TITLE
Erreur linter too few methods

### ISSUE THREAD

**Issue by damdamo** [akb89/nima#29]
Dans chacune des classes du preprocessing il y a une seule méthode tandis qu'il en faut au moins deux pour que cela passe avec le linter.
Le problème peut se voir dans le fichier tokenizer.py / lowercaser.py /lemmatizer.py

Je ne vais pas créer une méthode inutile juste pour faire passer le linter.
De plus j'ai du rajouté le décorateur @staticmethod pour les méthodes existantes pour ne pas avoir le message d'erreur:
"Method could be a function"

**Comment by akb89** [comment]
I removed the class-based architecture. Problem solved
