### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by akb89** [akb89/nima#3]
@enzopoggio @damdamo 
I have been thinking a bit more about the structure and I realized that it would be better to name scripts with nouns rather than verbs.
Then the scripts should contain functions with verb naming conventions:
```
def validate_preprocessing():
    pass
```
As functions should be actions exemplified by verbs. 
I will branch team1 to team1_dev tonight to show you what I have in mind. 
Let me know what you think. 
I will leave the issue open until we reach a consensus. I also need to ask around to more experienced developers to see whether or not it would be a good idea. I'll get back to you by tomorrow with more ideas if necessary. Don't hesitate to comment the issue.

**Comment by enzopoggio** [comment]
yes it should be better because now it's like this: 
`from extract import extract_from_xml_to_json`
this is redundant
it would be better if it was :
`from extractor import extract_from_xml_to_json`
it's the function of the script which extract not the script itself

**Comment by akb89** [comment]
Note that I prefer never to import functions but always the scripts which contains the functions to avoid ambiguity about where the function was originally defined.

**Comment by enzopoggio** [comment]
Okay I will change it

**Comment by akb89** [comment]
@enzopoggio @damdamo 
I have integrated your changes to the team1_dev branch, and refactored them (a bit). I'll continue tomorrow. If you agree, we'll merge the team1_dev branch to the team1 branch so you will be able to work on the team1 branch.
