### ISSUE TITLE
Should the user can choose which symbols break lines in the extractor? 

### ISSUE THREAD

**Issue by EPgg92** [akb89/nima#31]
Imagine the user want to preprocess his corpus and cut code on the comma (or what ever) too! Should we have a config file to let him choose what he want as separator char?

**Comment by EPgg92** [comment]
check what have done ? and tell me what do you think about !

**Comment by akb89** [comment]
@EPgg92 I think sentence split should follow some sort of standard (valid across languages) and shouldn't be left to the user to enforce consistency across data processing. 
For instance, we may consider that only ?!.。？！؟!.  should be taken as sentence ending symbols, but not matter what we should this should be hard-coded in constants.py and not in the config. 
Also, we may want to separate lists of symbols by language of alphabet families to make debugging easier.
