### ISSUE TITLE
too much parameter 

### ISSUE THREAD

**Issue by EPgg92** [akb89/nima#32]
Hi if we have too many parameter for a function can we use namedtuple?

**Comment by akb89** [comment]
Actually, I am considering converting the config loaded from yaml to an immutable dict which would be passed as parameters (the full dict or subdicts) of every function. 
This would remove the overhead of having too many parameters in functions and having to refactor the whole pipeline when parameters are added to the config. The code would definitely be more flexible and the app more scalable. 
I will add an issue to NiMa and inform everyone and I will take care of the refactoring.
