### ISSUE TITLE
WikiExtractor the AA folder ?

### ISSUE THREAD

**Issue by enzopoggio** [akb89/nima#4]
Hi,
I'm worried about WikiExtractor! 
It creates a folder AA in the output ( *-o* ) then a file wiki_00 which contains what we want.
I don't know what the AA means, but i hope that WikiExtractor doesn't create AB or AC folder !
Can you extract with more than one article ? Or provide us a dump with more articles?
Further we need to know the data structure created by WikiExtractor of the json file when we got more than one article.

**Comment by akb89** [comment]
Ok I'm on it I'll take care of this tomorrow

**Comment by enzopoggio** [comment]
Thanks

**Comment by akb89** [comment]
Wikiextractor is now called as a module with a custom function which returns json objects and does not write to file directly. Closing the issue.
