### ISSUE TITLE
Problème avec pylint

### ISSUE THREAD

**Issue by damdamo** [akb89/nima#5]
Un problème dérangeant avec pylint fait que quand nous déclarons une variable en python comme:
example = 3
Celui-ci n'aime pas et pense que c'est une constante. J'ai trouvé un thread sur stackoverflow expliquant le soucis: http://stackoverflow.com/questions/41204932/python-pylint-c0103invalid-constant-name
Voici la doc qui montre ce qu'attend le linter en fonction des types de variables:
http://pylint-messages.wikidot.com/messages:c0103
Serait-il possible de modifier la regex des constantes pour accepter aussi les minuscules dans le nom, sinon nous sommes obligé de tout mettre en majuscule.

**Comment by akb89** [comment]
If you are not reassigning your variable, it is indeed a constant :-) 

It is considered good practice to use upper case for constants (and not only in python).

**Comment by damdamo** [comment]
Donc si je déclare un dictionnaire dans mes fonctions et dans le "_name__ == '__main__':"
je peux les mettre tout en majuscule?
J'ai push mon code, tu peux voir l'exemple dans le fichier "tokenize_text.py" avec example_dictionnary.

**Comment by akb89** [comment]
Si c'est une variable, ça doit rester en minuscule. Si c'est une constante, ça doit être en majuscule.

**Comment by damdamo** [comment]
Oui je suis d'accord, mais pylint considère les variables comme des constantes. Je ne suis pas le seul à avoir le soucis vu que je le trouve souvent sur stackoverflow. 
Le simple fait de définir:
```bash
my_dic = {}   
my_dic["text"] = "Hello World!"
print(my_dic)
```
Dans ce cas my_dic est souligné et compté comme une constante et non une variable.

**Comment by akb89** [comment]
Which version of pylint do you have? I can't reproduce the error

**Comment by damdamo** [comment]
Pylint 1.7.1
