### ISSUE TITLE
Questions à propos __init__

### ISSUE THREAD

**Issue by damdamo** [akb89/nima#9]
Enzo et moi ne comprenons pas comment fonctionne les fichiers __init__. Nous avons des difficultés avec les imports de nos modules. Serait-il possible d'avoir un exemple simple pour comprendre comment ceux-ci s'utilisent?

**Comment by akb89** [comment]
Vous auriez un exemple de ce qui ne marche pas ?

**Comment by enzopoggio** [comment]
Alors nous avons essayer de régler le problème dans le dernier push que l'on vient de faire  est-ce que tu peux nous dire si c'est la bonne pratique que de faire de cette manière !
Pour le moment notre main marche ! 
Mais on peux pas passer le built à cause de deux import :
dans tokenize_text_with_nltk.py:
`from nltk.tokenize import TweetTokenizer`
et dans : 
lemmatize_with_nltk.py
`import nltk.stem.lancaster as lancaster`

**Comment by enzopoggio** [comment]
désolé mauvais bouton

**Comment by akb89** [comment]
Déjà il ne faut pas utiliser `from ***` comme indiqué dans les guidelines
Ensuite, arrêtez les commits pcq vous êtes en train de travailler sur la mauvaise structure de projet. 
Je vais merger dev avec team1, intégrer vos changement, et ensuite je reviens vers vous

**Comment by akb89** [comment]
@enzopoggio @damdamo Je vais vous coder un exemple concret et propre sur la base de ce que vous avez déjà fait en incluant le logging et les générateurs puis je reviens vers vous. Ça va me prendre un peu de temps par contre, au moins une heure.

**Comment by akb89** [comment]
@enzopoggio @damdamo Désolé pour le retard, je suis encore dessus. J'avance le plus possible et je reviens vers vous pour que vous ayez qqch de bien structuré. Je vais essayer de finir ce soir ou demain matin.

**Comment by enzopoggio** [comment]
Pas de problème ! (T'inquiète pas pour le retard on a d'autres projets qui nous occupent)

**Comment by akb89** [comment]
@enzopoggio @damdamo Voilà je vous ai recodé la structure générale de l'application ainsi que l'extractor avec des examples de config, gestion d'erreur et utilisation des générateurs. Tout est mergé dans la branche team1. J'ai du recoder une partie de wikiextractor pour pouvoir l'utiliser comme module et c'est ça qui m'a pris le plus de temps, mais maintenant ça marche. 
Je vous propose de commencer par améliorer l'extractor, le linter, le tester, le commenter proprement et résoudre les quelques bugs qui restent. Je vais ouvrir des issues avec les détails de ce qui manque. **Ne touchez surtout pas au preprocessing**, je dois encore finir la structure globale, je voudrais faire quelquechose de fonctionnel. J'ai ma petite idée mais ça va prendre du temps, un ou deux jours.   

Je vous laisse regarder en détails pcq la structure a pas mal changée. N'hésitez-pas s'il y a des choses que vous ne comprenez pas et souvenez-vous que chacun de mes choix (même les mauvais !) a une explication :-)
